# This is a special configuration to allow the shell to run in the serial terminal
# interface. It allows setting the CAN nodeid, for example.
# Build instructions:
#   west build -p -- -DEXTRA_CONF_FILE=overlay_shell.conf

CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_MODE_IMMEDIATE=n
CONFIG_LOG_BUFFER_SIZE=20480

CONFIG_SHELL=y
CONFIG_SHELL_LOG_BACKEND=y

# enable this to add i2c interface scanning, for example
#CONFIG_I2C_SHELL=y
