CONFIG_GPIO=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE=y
# CONFIG_MCUBOOT_SIGNATURE_KEY_FILE=""
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_MCUBOOT_GENERATE_CONFIRMED_IMAGE=n
CONFIG_CAN=y
CONFIG_CANOPENNODE=y
CONFIG_CANOPENNODE_PROGRAM_DOWNLOAD=y
CONFIG_CAN_MAX_FILTER=13
CONFIG_CANOPENNODE_SDO_BUFFER_SIZE=889

CONFIG_REBOOT=y

#CONFIG_ORESAT_COMMON_LIB=y

CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y

CONFIG_DAC=y

CONFIG_ADC=y
CONFIG_SEQUENCE_SAMPLES=8
CONFIG_ADC_STM32=y
CONFIG_ADC_STM32_DMA=y

CONFIG_DMA=y
CONFIG_DMA_STM32=y
CONFIG_DMA_LOG_LEVEL_WRN=y

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=2048
CONFIG_LOG_PRINTK=y

CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_SENSOR_LOG_LEVEL_DBG=y
CONFIG_KERNEL_LOG_LEVEL_INF=y
CONFIG_ADC_LOG_LEVEL_INF=y
CONFIG_DAC_LOG_LEVEL_DBG=y

CONFIG_HEAP_MEM_POOL_SIZE=256
CONFIG_ASSERT=y
