CONFIG_GPIO=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

CONFIG_CAN_MAX_FILTER=12
CONFIG_CANOPENNODE_SDO_BUFFER_SIZE=889
CONFIG_CAN_DEFAULT_BITRATE=1000000
CONFIG_CANOPENNODE_SYNC_THREAD=n

CONFIG_REBOOT=y

CONFIG_ORESAT_COMMON_LIB=y

CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y

CONFIG_BLINK_DEMO=y
CONFIG_I2C_SENSOR_DEMO=y
CONFIG_CAN_DEMO=y
CONFIG_ADC_DEMO=y
CONFIG_DAC_DEMO=y
CONFIG_GPIO_DEMO=y

# Below is required to read temperature channel 26,
# but it causes a bus fault. Debug required.
#CONFIG_LPADC_CHANNEL_COUNT=28

CONFIG_SEQUENCE_SAMPLES=8

CONFIG_DMA_LOG_LEVEL_WRN=y

CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_MODE_DEFERRED=n
#CONFIG_LOG_BUFFER_SIZE=20480
CONFIG_LOG_PRINTK=y

CONFIG_LOG_DEFAULT_LEVEL=4
#CONFIG_SENSOR_LOG_LEVEL_DBG=y
CONFIG_KERNEL_LOG_LEVEL_INF=y
CONFIG_ADC_LOG_LEVEL_INF=y
CONFIG_DAC_LOG_LEVEL_INF=y

CONFIG_HEAP_MEM_POOL_SIZE=1024
CONFIG_ASSERT=y

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048

CONFIG_ASSERT=n
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_COVERAGE=n

CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_USE_PRINTK=y
CONFIG_THREAD_ANALYZER_AUTO=y
CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=300

CONFIG_INIT_STACKS=y
CONFIG_STACK_SENTINEL=y
#CONFIG_STACK_CANARIES=y
#CONFIG_TEST_RANDOM_GENERATOR=y
