// clang-format off
/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode v1 to v2

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
*******************************************************************************/
#ifndef CO_OD_H_
#define CO_OD_H_

/*******************************************************************************
   CANopen DATA TYPES
*******************************************************************************/
   typedef bool_t       BOOLEAN;
   typedef uint8_t      UNSIGNED8;
   typedef uint16_t     UNSIGNED16;
   typedef uint32_t     UNSIGNED32;
   typedef uint64_t     UNSIGNED64;
   typedef int8_t       INTEGER8;
   typedef int16_t      INTEGER16;
   typedef int32_t      INTEGER32;
   typedef int64_t      INTEGER64;
   typedef float32_t    REAL32;
   typedef float64_t    REAL64;
   typedef char_t       VISIBLE_STRING;
   typedef oChar_t      OCTET_STRING;

   #ifdef DOMAIN
   #undef DOMAIN
   #endif

   typedef domain_t     DOMAIN;


/*******************************************************************************
   FILE INFO:
      FileName:     batt.xdd
      FileVersion:  1
      CreationTime: 2:12PM
      CreationDate: 12-06-2025
      CreatedBy:    
*******************************************************************************/


/*******************************************************************************
   DEVICE INFO:
      VendorName:     PSAS
      VendorNumber:   0
      ProductName:    Oresat Battery Card
      ProductNumber:  3
*******************************************************************************/


/*******************************************************************************
   FEATURES
*******************************************************************************/
  #define CO_NO_SYNC                     0   //Associated objects: 1005-1007
  #define CO_NO_EMERGENCY                0   //Associated objects: 1014, 1015
  #define CO_NO_TIME                     0   //Associated objects: 1012, 1013
  #define CO_NO_SDO_SERVER               0   //Associated objects: 1200-127F
  #define CO_NO_SDO_CLIENT               0   //Associated objects: 1280-12FF
  #define CO_NO_GFC                      0   //Associated objects: 1300
  #define CO_NO_SRDO                     0   //Associated objects: 1301-1341, 1381-13C0
  #define CO_NO_LSS_SERVER               0   //LSS Slave
  #define CO_NO_LSS_CLIENT               0   //LSS Master
  #define CO_NODE_GUARDING_SLAVE         0   //NG Slave
  #define CO_NODE_GUARDING_MASTER        0   //NG Master
  #define CO_NO_RPDO                     0   //Associated objects: 14xx, 16xx
  #define CO_NO_TPDO                     10   //Associated objects: 18xx, 1Axx
  #define CO_NO_NMT_MASTER               0
  #define CO_NO_TRACE                    0


/*******************************************************************************
   OBJECT DICTIONARY
*******************************************************************************/
   #define CO_OD_NoOfElements             22


/*******************************************************************************
   TYPE DEFINITIONS FOR RECORDS
*******************************************************************************/
/*1800      */ typedef struct {
               UNSIGNED8      highestSubIndexSupported;
               UNSIGNED32     COB_IDUsedByTPDO;
               UNSIGNED8      transmissionType;
               UNSIGNED16     inhibitTime;
               UNSIGNED8      compatibilityEntry;
               UNSIGNED16     eventTimer;
               UNSIGNED8      SYNCStartValue;
               }              OD_TPDOCommunicationParameter_t;
/*1A00      */ typedef struct {
               UNSIGNED8      numberOfMappedApplicationObjectsInPDO;
               UNSIGNED32     applicationObject1;
               UNSIGNED32     applicationObject2;
               UNSIGNED32     applicationObject3;
               UNSIGNED32     applicationObject4;
               UNSIGNED32     applicationObject5;
               UNSIGNED32     applicationObject6;
               UNSIGNED32     applicationObject7;
               UNSIGNED32     applicationObject8;
               }              OD_TPDOMappingParameter_t;
/*4000      */ typedef struct {
               UNSIGNED8      maxSubIndex;
               UNSIGNED16     vbatt;
               UNSIGNED16     vcell_max;
               UNSIGNED16     vcell_min;
               UNSIGNED16     vcell;
               UNSIGNED16     vcell_1;
               UNSIGNED16     vcell_2;
               UNSIGNED16     vcell_avg;
               INTEGER16      current;
               INTEGER16      current_avg;
               INTEGER16      current_max;
               INTEGER16      current_min;
               UNSIGNED16     full_capacity;
               UNSIGNED16     reported_capacity;
               UNSIGNED16     time_to_empty;
               UNSIGNED16     time_to_full;
               UNSIGNED16     cycles;
               UNSIGNED8      reported_state_of_charge;
               INTEGER8       temperature;
               INTEGER8       temperature_avg;
               INTEGER8       temperature_max;
               INTEGER8       temperature_min;
               UNSIGNED8      status;
               }              OD_pack_1_t;
/*4001      */ typedef struct {
               UNSIGNED8      highestSubIndexSupported;
               UNSIGNED16     vbatt;
               UNSIGNED16     vcell_max;
               UNSIGNED16     vcell_min;
               UNSIGNED16     vcell;
               UNSIGNED16     vcell_1;
               UNSIGNED16     vcell_2;
               UNSIGNED16     vcell_avg;
               INTEGER16      current;
               INTEGER16      current_avg;
               INTEGER16      current_max;
               INTEGER16      current_min;
               UNSIGNED16     full_capacity;
               UNSIGNED16     reported_capacity;
               UNSIGNED16     time_to_empty;
               UNSIGNED16     time_to_full;
               UNSIGNED16     cycles;
               UNSIGNED8      reported_state_of_charge;
               INTEGER8       temperature;
               INTEGER8       temperature_avg;
               INTEGER8       temperature_max;
               INTEGER8       temperature_min;
               UNSIGNED8      status;
               }              OD_pack_2_t;

/*******************************************************************************
   TYPE DEFINITIONS FOR OBJECT DICTIONARY INDEXES

   some of those are redundant with CO_SDO.h CO_ObjDicId_t <Common CiA301 object
   dictionary entries>
*******************************************************************************/
/*1800 */
        #define OD_1800_TPDOCommunicationParameter                  0x1800

        #define OD_1800_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1800_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1800_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1800_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1800_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1800_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1800_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1801 */
        #define OD_1801_TPDOCommunicationParameter                  0x1801

        #define OD_1801_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1801_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1801_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1801_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1801_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1801_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1801_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1802 */
        #define OD_1802_TPDOCommunicationParameter                  0x1802

        #define OD_1802_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1802_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1802_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1802_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1802_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1802_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1802_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1803 */
        #define OD_1803_TPDOCommunicationParameter                  0x1803

        #define OD_1803_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1803_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1803_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1803_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1803_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1803_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1803_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1804 */
        #define OD_1804_TPDOCommunicationParameter                  0x1804

        #define OD_1804_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1804_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1804_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1804_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1804_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1804_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1804_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1805 */
        #define OD_1805_TPDOCommunicationParameter                  0x1805

        #define OD_1805_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1805_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1805_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1805_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1805_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1805_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1805_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1806 */
        #define OD_1806_TPDOCommunicationParameter                  0x1806

        #define OD_1806_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1806_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1806_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1806_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1806_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1806_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1806_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1807 */
        #define OD_1807_TPDOCommunicationParameter                  0x1807

        #define OD_1807_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1807_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1807_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1807_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1807_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1807_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1807_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1808 */
        #define OD_1808_TPDOCommunicationParameter                  0x1808

        #define OD_1808_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1808_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1808_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1808_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1808_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1808_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1808_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1809 */
        #define OD_1809_TPDOCommunicationParameter                  0x1809

        #define OD_1809_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1809_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1809_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1809_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1809_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1809_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1809_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1A00 */
        #define OD_1A00_TPDOMappingParameter                        0x1A00

        #define OD_1A00_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A00_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A00_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A00_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A00_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A00_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A00_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A00_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A00_8_TPDOMappingParameter_applicationObject8   8

/*1A01 */
        #define OD_1A01_TPDOMappingParameter                        0x1A01

        #define OD_1A01_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A01_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A01_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A01_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A01_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A01_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A01_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A01_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A01_8_TPDOMappingParameter_applicationObject8   8

/*1A02 */
        #define OD_1A02_TPDOMappingParameter                        0x1A02

        #define OD_1A02_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A02_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A02_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A02_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A02_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A02_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A02_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A02_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A02_8_TPDOMappingParameter_applicationObject8   8

/*1A03 */
        #define OD_1A03_TPDOMappingParameter                        0x1A03

        #define OD_1A03_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A03_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A03_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A03_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A03_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A03_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A03_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A03_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A03_8_TPDOMappingParameter_applicationObject8   8

/*1A04 */
        #define OD_1A04_TPDOMappingParameter                        0x1A04

        #define OD_1A04_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A04_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A04_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A04_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A04_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A04_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A04_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A04_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A04_8_TPDOMappingParameter_applicationObject8   8

/*1A05 */
        #define OD_1A05_TPDOMappingParameter                        0x1A05

        #define OD_1A05_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A05_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A05_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A05_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A05_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A05_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A05_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A05_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A05_8_TPDOMappingParameter_applicationObject8   8

/*1A06 */
        #define OD_1A06_TPDOMappingParameter                        0x1A06

        #define OD_1A06_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A06_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A06_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A06_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A06_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A06_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A06_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A06_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A06_8_TPDOMappingParameter_applicationObject8   8

/*1A07 */
        #define OD_1A07_TPDOMappingParameter                        0x1A07

        #define OD_1A07_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A07_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A07_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A07_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A07_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A07_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A07_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A07_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A07_8_TPDOMappingParameter_applicationObject8   8

/*1A08 */
        #define OD_1A08_TPDOMappingParameter                        0x1A08

        #define OD_1A08_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A08_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A08_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A08_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A08_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A08_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A08_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A08_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A08_8_TPDOMappingParameter_applicationObject8   8

/*1A09 */
        #define OD_1A09_TPDOMappingParameter                        0x1A09

        #define OD_1A09_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A09_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A09_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A09_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A09_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A09_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A09_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A09_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A09_8_TPDOMappingParameter_applicationObject8   8

/*4000 */
        #define OD_4000_pack_1                                      0x4000

        #define OD_4000_0_pack_1_maxSubIndex                        0
        #define OD_4000_1_pack_1_vbatt                              1
        #define OD_4000_2_pack_1_vcell_max                          2
        #define OD_4000_3_pack_1_vcell_min                          3
        #define OD_4000_4_pack_1_vcell                              4
        #define OD_4000_5_pack_1_vcell_1                            5
        #define OD_4000_6_pack_1_vcell_2                            6
        #define OD_4000_7_pack_1_vcell_avg                          7
        #define OD_4000_8_pack_1_current                            8
        #define OD_4000_9_pack_1_current_avg                        9
        #define OD_4000_10_pack_1_current_max                       10
        #define OD_4000_11_pack_1_current_min                       11
        #define OD_4000_12_pack_1_full_capacity                     12
        #define OD_4000_13_pack_1_reported_capacity                 13
        #define OD_4000_14_pack_1_time_to_empty                     14
        #define OD_4000_15_pack_1_time_to_full                      15
        #define OD_4000_16_pack_1_cycles                            16
        #define OD_4000_17_pack_1_reported_state_of_charge          17
        #define OD_4000_18_pack_1_temperature                       18
        #define OD_4000_19_pack_1_temperature_avg                   19
        #define OD_4000_20_pack_1_temperature_max                   20
        #define OD_4000_21_pack_1_temperature_min                   21
        #define OD_4000_22_pack_1_status                            22

/*4001 */
        #define OD_4001_pack_2                                      0x4001

        #define OD_4001_0_pack_2_maxSubIndex                        0
        #define OD_4001_1_pack_2_vbatt                              1
        #define OD_4001_2_pack_2_vcell_max                          2
        #define OD_4001_3_pack_2_vcell_min                          3
        #define OD_4001_4_pack_2_vcell                              4
        #define OD_4001_5_pack_2_vcell_1                            5
        #define OD_4001_6_pack_2_vcell_2                            6
        #define OD_4001_7_pack_2_vcell_avg                          7
        #define OD_4001_8_pack_2_current                            8
        #define OD_4001_9_pack_2_current_avg                        9
        #define OD_4001_10_pack_2_current_max                       10
        #define OD_4001_11_pack_2_current_min                       11
        #define OD_4001_12_pack_2_full_capacity                     12
        #define OD_4001_13_pack_2_reported_capacity                 13
        #define OD_4001_14_pack_2_time_to_empty                     14
        #define OD_4001_15_pack_2_time_to_full                      15
        #define OD_4001_16_pack_2_cycles                            16
        #define OD_4001_17_pack_2_reported_state_of_charge          17
        #define OD_4001_18_pack_2_temperature                       18
        #define OD_4001_19_pack_2_temperature_avg                   19
        #define OD_4001_20_pack_2_temperature_max                   20
        #define OD_4001_21_pack_2_temperature_min                   21
        #define OD_4001_22_pack_2_status                            22

/*******************************************************************************
   STRUCTURES FOR VARIABLES IN DIFFERENT MEMORY LOCATIONS
*******************************************************************************/
#define  CO_OD_FIRST_LAST_WORD     0x55 //Any value from 0x01 to 0xFE. If changed, EEPROM will be reinitialized.

/***** Structure for RAM variables ********************************************/
struct sCO_OD_RAM{
               UNSIGNED32     FirstWord;

/*4000      */ OD_pack_1_t     pack_1;
/*4001      */ OD_pack_2_t     pack_2;

               UNSIGNED32     LastWord;
};

/***** Structure for ROM variables ********************************************/
struct sCO_OD_ROM{
               UNSIGNED32     FirstWord;


               UNSIGNED32     LastWord;
};

/***** Structure for EEPROM variables ********************************************/
struct sCO_OD_EEPROM{
               UNSIGNED32     FirstWord;


               UNSIGNED32     LastWord;
};

/***** Structure for PERSIST_COMM variables ********************************************/
struct sCO_OD_PERSIST_COMM{
               UNSIGNED32     FirstWord;

/*1800      */ OD_TPDOCommunicationParameter_t TPDOCommunicationParameter[10];
/*1A00      */ OD_TPDOMappingParameter_t TPDOMappingParameter[10];

               UNSIGNED32     LastWord;
};

/***** Declaration of Object Dictionary variables *****************************/
extern struct sCO_OD_RAM CO_OD_RAM;

extern struct sCO_OD_ROM CO_OD_ROM;

extern struct sCO_OD_EEPROM CO_OD_EEPROM;

extern struct sCO_OD_PERSIST_COMM CO_OD_PERSIST_COMM;

/*******************************************************************************
   ALIASES FOR OBJECT DICTIONARY VARIABLES
*******************************************************************************/
/*1800, Data Type: TPDOCommunicationParameter_t */
        #define OD_TPDOCommunicationParameter_idx                   0x1800
        #define OD_TPDOCommunicationParameter                       CO_OD_PERSIST_COMM.TPDOCommunicationParameter

/*1A00, Data Type: TPDOMappingParameter_t */
        #define OD_TPDOMappingParameter_idx                         0x1A00
        #define OD_TPDOMappingParameter                             CO_OD_PERSIST_COMM.TPDOMappingParameter

/*4000, Data Type: pack_1_t */
        #define OD_pack_1_idx                                       0x4000
        #define OD_pack_1                                           CO_OD_RAM.pack_1

/*4001, Data Type: pack_2_t */
        #define OD_pack_2_idx                                       0x4001
        #define OD_pack_2                                           CO_OD_RAM.pack_2

#endif
// clang-format on
